name: Timothy Lynn
title: TIMMEH!
permalink: /posts/:year/:month/:day/:title
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Tim"
plugins:
  - jekyll-sitemap