name: Timothy Lynn
title: Timothy Lynn
permalink: /posts/:year/:month/:day/:title
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "post"
      author: "Timothy Lynn"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
repository: pacifisticuffs/pacifisticuffs.github.io
url: http://timothylynn.com
author:
  name: Timothy Lynn